// ignore_for_file: constant_identifier_names

abstract class AppStrings {
  static const String
      //On Boarding Strings
      skip = "Skip",
      next = "Next",
      createAccount = "Create New Account",
      loginNow = "Login Now",
      //Auth Strings
      welcome = "Welcome To Cognme",
      welcomeBack = "Welcome Back!",
      name = "First Name",
      lastName = "Last Name",
      emailAddress = "Email Address",
      password = "Password",
      iHaveAgreeToOur = "I have agree to our ",
      termsAndCondition = "Terms and Condition",
      signUp = "Sign Up",
      signIn = "Sign In",
      alreadyHaveAnAccount = "Already have an account ? ",
      dontHaveAnAccount = "Don’t have an account ? ",
      forgotPassword = "Forgot Password ?",
      profile = "Profile",
      account = "Account",
      editProfile = "Edit Profile",
      notification = "Notification",
      general = "General",
      settings = "Settings",
      security = "Security",
      privacyPolicy = "Privacy Policy",
      logOut = "Log Out",
      backToHome = "Back To Home",
      confirmPassword = "Confirm Password",
      //Forgot password
      forgotPasswordPage = "Forgot Password",
      sendResetPasswordLink = "Send Reset password Link",
      verificationNow = "Verification Now",
      resendCode = "Resend Code",
      verifyAccount = "Verify Account",
      enter4DigitCodeWeHaveSentTo = "Enter 4 digit code we have sent to ",
      haventReceivedVerificationCode = "Haven’t received verification code?",
      homewelcom = "Good morning",
      Mansoura = ' Mansoura, EGY',
      Monday = ' Monday, June',
      coolWears = 'Cool Wears',
      moreOptions = 'more options',
      physicians = 'Physicians',
      doctorName = 'Dr. Ahmed Lotfy',
      doctorDisc = 'Ear, Nose and Throat Surgery ',
      doctorLocation = ' In front of the Faculty of Islamic  ',
      phone = 'Phone',
      appointments = "Appointments",
      nameContact = 'Name';
}
